### ISSUE TITLE
Implement a better hash

### ISSUE THREAD

**Issue by Mrtenz** [Shadow48402/MySQL-Register#2]
MD5 is not safe and shouldn't be used for hashing passwords.

**Comment by Shadow48402** [comment]
The hash is configurable as far as I can remember:
`CoreManager.hash(args[1], c.getString("Hash"))`

**Comment by Mrtenz** [comment]
This only supports MD5 and SHA-1 AFAIK. A hash like Bcrypt or PBKDF2 should be used.

**Comment by Shadow48402** [comment]
As far as I know does it support all algorithms in the link bellow, I am 100% sure that it support SHA-256 I didn't test any other hash.

http://docs.oracle.com/javase/7/docs/technotes/guides/security/StandardNames.html
